import type { Service } from './types';

// Service names mirror the live site's "Areas of Expertise" grid.
// `href`: internal path (built as a local page), full URL (external), or null (no link).
export const SERVICES: readonly Service[] = [
  {
    slug: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    blurb: 'Applied AI and machine learning for network and telecom data.',
    icon: 'ai-icon',
    href: 'https://bluescarf.ai/',
  },
  {
    slug: 'automation',
    name: 'Automation Services',
    blurb: 'Infrastructure, test, and workflow automation across the stack.',
    icon: 'automation',
    href: '/automation',
  },
  {
    slug: 'api',
    name: 'Application Programming Interface',
    blurb: 'Design and delivery of REST and telecom APIs.',
    icon: 'api-dev',
    href: '/api',
  },
  {
    slug: 'cloud-and-devops-services',
    name: 'Cloud and DevOps Services',
    blurb: 'Cloud-native platforms, CI/CD pipelines, and DevOps practice.',
    icon: 'cloud-cservice',
    href: '/cloud-and-devops-services',
  },
  {
    slug: 'cyber-security',
    name: 'Cyber Security',
    blurb: 'Security engineering, hardening, and assessments.',
    icon: 'cyber-security-icon',
    href: null,
  },
  {
    slug: 'databases-and-storage',
    name: 'Databases and Storage',
    blurb: 'Data platforms, storage design, and analytics pipelines.',
    icon: 'databases-symbol',
    href: '/coming-soon',
  },
  {
    slug: 'gis',
    name: 'Geographical Information Systems (GIS)',
    blurb: 'Spatial data platforms and mapping solutions.',
    icon: 'gis',
    href: '/gis',
  },
  {
    slug: 'gis-in-telecommunication',
    name: 'GIS in Telecommunication',
    blurb: 'Geospatial analytics for network planning and operations.',
    icon: 'gis-telco',
    href: null,
  },
  {
    slug: 'monitoring-solutions',
    name: 'Monitoring Solutions',
    blurb: 'Observability, telemetry, and performance monitoring.',
    icon: 'monitoring-performance',
    href: '/monitoring-solutions',
  },
  {
    slug: 'nfv',
    name: 'NFV Infrastructure',
    blurb: 'NFV infrastructure development, automation, and orchestration.',
    icon: 'mano-icon',
    href: '/nfv',
  },
  {
    slug: 'open-source-contributions-and-development',
    name: 'OpenSource Contributions and Development',
    blurb: 'Upstream contributions to networking and cloud projects.',
    icon: 'dpi-icon',
    href: '/open-source-contributions-and-development',
  },
  {
    slug: 'professional-services',
    name: 'Professional Services',
    blurb: 'Consulting, architecture, and delivery support.',
    icon: 'professional',
    href: '/professional-services',
  },
  {
    slug: 'project-management',
    name: 'Project Management Services',
    blurb: 'Programme and delivery management for technical projects.',
    icon: 'project-management',
    href: '/project-management',
  },
  {
    slug: 'quantum-research',
    name: 'Quantum Research',
    blurb: 'Research into quantum computing and communications.',
    icon: 'quantum-computer',
    href: null,
  },
  {
    slug: 'research-and-standardization',
    name: 'Research and Standardization',
    blurb: 'Participation in standards bodies and applied research.',
    icon: 'lucide:award',
    href: '/research-and-standardization',
  },
  {
    slug: 'software-development',
    name: 'Software Development',
    blurb: 'Custom software for networking, telecom, and cloud.',
    icon: 'programming-svgrepo-com',
    href: '/software-development',
  },
  {
    slug: 'sonic',
    name: 'SONiC Network Operating System (NOS)',
    blurb: 'SONiC development, porting, and platform bring-up.',
    icon: 'sonic-icon',
    href: '/sonic',
  },
  {
    slug: 'testing-and-validation',
    name: 'Testing and Validation',
    blurb: 'Benchmarking, profiling, and conformance testing.',
    icon: 'testing-validation',
    href: '/testing-and-validation',
  },
  {
    slug: 'training-services',
    name: 'Training Services',
    blurb: 'Training and certification in SDN, NFV, and OpenStack.',
    icon: 'training',
    href: '/coming-soon',
  },
  {
    slug: 'technical-support',
    name: 'Technical Support',
    blurb: 'Ongoing support for deployed platforms and solutions.',
    icon: 'support',
    href: '/coming-soon',
  },
  {
    slug: 'vulnerability-assessment-services',
    name: 'Vulnerability Assessment Services',
    blurb: 'Vulnerability scanning and remediation guidance.',
    icon: 'vulnerability-scan-services-icon',
    href: null,
  },
  {
    slug: 'web-application',
    name: 'Web Application',
    blurb: 'Web application design, build, and delivery.',
    icon: 'web-development',
    href: '/web-application',
  },
];

/** Services that get their own local page (internal href, not "/coming-soon"). */
export const SERVICE_PAGES = SERVICES.filter(
  (s) => s.href?.startsWith('/') && s.href !== '/coming-soon',
);
