import type { ServiceContent } from './types';

// Body content for each service that has its own local page, mirrored from the
// live site's service pages (xflowresearch.com). Keyed by `Service.slug`;
// services without an entry fall back to rendering just their `blurb`.

export const SERVICE_CONTENT: Record<string, ServiceContent> = {
  'automation': {
    blocks: [
      { type: 'para', runs: ['Deployment automation is a significant aspect of our services, and it can save time, reduce errors, and increase the reliability of the solution. Similarly, automated testing reduces the amount of manual intervention required, and it ensures that the tests are run in a consistent and repeatable manner.'] },
      { type: 'para', runs: ['We provide our automation services to data centers to perform their day to day operations. This includes:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Day 0 operations: bringing up network devices into a functional state with minimal to no-touch. At the end of Day 0, customers have a fresh machine installed and handed over'],
          ['Day 1 operations: configuring the components in the data center to meet business needs and requirements. configuration of VLANs, routing protocols, security protocols, ACLs etc.'],
          ['Day 2 operations: the data center gets turned over to production'],
          ['Day 2+1 operations: includes upgrading the NFs to new software, patching for bugs and scaling up or scaling down NFs based on SLAs (Service Level Agreements)'],
        ],
      },
      { type: 'para', runs: ['We also provide end-to-end zero-touch provisioning (ZTP) deployment solutions for cloud infrastructure platforms including OpenStack and OpenShift. Our goal is to simplify and streamline the deployment process, reducing the time and effort required to set up the cloud, while ensuring consistency and reliability across multiple deployments. It covers all of the aspects including network automation, setting up basic underlying networking, provisioning and managing the nodes, setting up RAID configurations, pre-packaged installations and much more.'] },
      { type: 'para', runs: ['We also provide comprehensive test automation services to improve software quality, accelerate release cycles, and reduce the effort involved in repetitive testing activities. Our team develops scalable and maintainable automation frameworks using ', { b: 'Pytest' }, ' for Python-based test automation and ', { b: 'Robot Framework' }, ' for keyword-driven testing. We automate functional, regression, API, integration, and end-to-end test scenarios, enabling consistent, repeatable, and reliable validation throughout the software development lifecycle. Our automation solutions integrate seamlessly with CI/CD pipelines, ensuring faster feedback, increased test coverage, and high-quality software deliveries.'] },
    ],
  },
  'api': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech also offers ', { b: 'API development services using Node.js' }, ', focusing on building lightweight and high-performance backend APIs. Our APIs are designed for internal systems, web applications, and third-party integrations, with an emphasis on clear structure, proper documentation, and scalability.'] },
    ],
  },
  'cloud-and-devops-services': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech has strong expertise in Cloud and DevOps. We can help organizations build software faster and more reliably through modern ', { b: 'Cloud and DevOps practices' }, '. We automate processes, manage cloud platforms, and build efficient pipelines that support continuous delivery and scalability.'] },
      { type: 'para', runs: ['Our key services include:'] },
      { type: 'heading', text: 'CI/CD Pipelines' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Set up and manage continuous integration and delivery using tools like Jenkins, GitLab CI, and GitHub Actions'],
          ['Automate build, test, and deployment processes'],
        ],
      },
      { type: 'heading', text: 'Cloud Platform Support' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Work with major cloud providers: Azure and AWS, and on prem deployments like OpenStack'],
          ['Handle cloud setup, migration, scaling, and cost optimization'],
        ],
      },
      { type: 'heading', text: 'Infrastructure as Code (IaC)' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Automate infrastructure with tools like Terraform, Ansible, and CloudFormation'],
          ['Maintain version-controlled and consistent environments'],
        ],
      },
      { type: 'heading', text: 'Containerization & Orchestration' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Use Docker for packaging applications'],
          ['Deploy and manage containers with Kubernetes and OpenShift'],
        ],
      },
      { type: 'heading', text: 'Monitoring & Alerts' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Implement tools like Prometheus, Grafana, and the ELK Stack'],
          ['Set up alerts and dashboards to track system health and performance'],
        ],
      },
      { type: 'heading', text: 'DevOps Best Practices' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Improve collaboration between development and operations teams'],
          ['Apply automation, security, and version control across workflows'],
        ],
      },
    ],
  },
  'cyber-security': {
    blocks: [
      { type: 'para', runs: ['We provide specialized services in:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Vulnerability Assessment and Penetration Testing (VAPT)'],
          ['Secure Software Development and Quality Assurance'],
          ['Governance, Risk, and Compliance'],
          ['Secure Architecture (Review/Audit/Plan/Design)'],
        ],
      },
      { type: 'heading', text: 'VAPT' },
      { type: 'para', runs: ['Vulnerability Assessment and Penetration Testing (VAPT) is an essential step in ensuring that an organization’s digital assets are secure from external and internal threats. It involves evaluating the security of an organization’s network, web applications, and mobile applications.'] },
      { type: 'heading', text: 'Our approach to VAPT' },
      { type: 'para', runs: ['We use commercial and open source tools to evaluate vulnerabilities in systems, and evaluate the vulnerabilities in the system for false positive or false negative based on our knowledge and understanding of known vulnerabilities. We provide risk ratings based on severity and ease of exploitation of the vulnerabilities'] },
      { type: 'para', runs: ['Our VAPT service is designed to help identify and address any security weaknesses in your organization’s network infrastructure, web applications, and mobile applications. We use a combination of manual and automated testing techniques adhering to security standards set by OWASP and NIST to identify vulnerabilities and weaknesses in your systems, then provide detailed reports outlining any identified security issues and how to remediate them. We also assess your applications for regulatory compliances such as PCI DSS and GDPR.'] },
      { type: 'heading', text: 'Coverage areas in VAPT' },
      { type: 'para', runs: ['We offer four main types of VAPT services: Web, Mobile and Cloud. Each type of VAPT service is unique and designed to address specific areas of concern for an organization.'] },
      {
        type: 'list',
        ordered: true,
        items: [
          [{ b: 'Web app VAPT:' }, ' Web VAPT involves assessing the security of an organization’s web applications. We test the security of web applications using a custom approach that covers the OWASP top 10 and SANS 25. The tests help identify vulnerabilities and potential weaknesses in web applications, allowing organizations to implement measures to prevent attacks. Our goal here is to analyze and attack all the functions of the websites to give an accurate security image of the websites where it will show which functions, webpages, or technology used is vulnerable in nature.'],
          [{ b: 'Mobile app VAPT:' }, ' Mobile VAPT involves assessing the security of an organization’s mobile applications. We test the security of mobile applications, including authentication, data storage, and data transmission to name a few using our custom approach that covers OWASP top 10. We analyze all aspects of the mobile application and initiate attacks against features to check whether it will cause any security failure or not by performing static and dynamic testing on these application'],
          [{ b: 'Cloud app VAPT:' }, ' Cloud VAPT involves assessing the security of an organization’s cloud-based infrastructure. More and more organizations rely on cloud services for their operations these days. We test the security of the cloud infrastructure, including cloud servers, virtual machines, and containers. The tests help identify vulnerabilities and potential weaknesses in the cloud environment, allowing organizations to implement measures to prevent attacks. In order to serve our clients with the best AI based penetration testing solutions, we have partnered with “ImmuniWeb” to test, secure and protect weband mobile applications, cloud and network infrastructure, and prevent supply chain attacks and data breaches, and to comply with regulatory requirements.'],
        ],
      },
      { type: 'heading', text: 'Secure Software Development & Quality Assurance' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Our ', { b: 'Secure Code Development' }, ' service is designed to help you develop and implement secure coding practices, ensuring that your software is secure from the outset. Our team of experts has extensive experience in developing secure code and can help you design, develop and maintain secure software applications that are resistant to cyber-attacks.'],
          ['We also offer Secure Code Review services. We review your software code to identify any potential vulnerabilities and provide recommendations on how to remediate them. Our Secure Code Review services are an essential component of our VAPT (Vulnerability Assessment and Penetration Testing) services and can help you ensure that your software is secure before deployment.'],
          ['We provide ', { b: 'Consultancy' }, ' on integrating state of the art software engineering and automated testing strategies in organizations, suggest improvements to software development and provide quality assurance processes, and data security for critical applications.'],
          ['We provide ', { b: 'Assessment and analysis of existing software' }, ' and test the quality and practices of the organizations to report on any information security threats to the organizations through their infrastructure and applications.'],
          ['Our teams provide ', { b: 'Independent Software Testing' }, ' or in Testing as a Service (TaaS) and validation & verification services to client organizations. The services range from manual and automated testing at system, integration, or unit levels to automated load and stress testing for web applications, mobile applications, desktop applications, and embedded systems.'],
          ['We perform ', { b: 'Security Testing' }, ' of critical applications for security threats, functional correctness, and scalability. The services include, automated penetration testing to assess network and application vulnerabilities, testing against known security vulnerabilities, e.g., OWASP vulnerabilities for web applications, and static analysis to identify source code vulnerabilities.'],
        ],
      },
      { type: 'heading', text: 'Governance, Risk and Compliance' },
      { type: 'para', runs: ['xFlow Tech’s Governance, Risk, and Compliance (GRC) solution assists enterprises in strengthening their overall security posture by minimizing risk exposure, assuring adherence to industry requirements, and aligning with information security best practices and standards.'] },
      { type: 'para', runs: ['Service we offer:'] },
      {
        type: 'list',
        ordered: true,
        items: [
          ['Cyber Maturity Assessment'],
          ['Risk Assessment'],
          ['Compliance Assessment'],
          ['Intelligent Data Services'],
        ],
      },
      { type: 'heading', text: 'Secure Architecture' },
      { type: 'para', runs: ['Secure Architecture Reviews are a collection of services based on industry best practices designed to evaluate the effectiveness of technical and operational security controls deployed in an organization. The reviews focus on People, Processes & Technology to improve the resilience of the organization’s security posture in consideration of Business Requirements, Best Practices referred to CIS Benchmarks, NIST CSF.'] },
      { type: 'para', runs: ['Services we offer:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Secure Architecture Review – Comprehensive maturity assessment of your architecture using Center for Internet controls (CIS 18)'],
          ['Network Security Assessment – Network scans to look for sensitive information and review of network design, protocols.'],
          ['Infrastructure Security review – Review the policies and technologies in use.'],
          ['Secure Configuration review – Review configurations of your critical Network Infrastructure against security benchmarks.'],
          ['Consulting Services – Planning & Deployment of networks from the ground up, Web Server Hardening, Firewall & Network secure configurations, Secure Data hosting'],
        ],
      },
    ],
  },
  'gis': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech is conducting GIS research across a range of spatial data domains to support advanced analysis and visualization. Our ongoing work includes:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          [{ b: 'Elevation Mapping' }, ' for terrain and geographic analysis'],
          [{ b: 'Rainfall Data Analysis' }, ' for weather and environmental insights'],
          [{ b: 'Soil Mapping' }, ' to support land and infrastructure assessment'],
          [{ b: 'Temperature Data Visualization' }, ' for climate and regional analysis'],
          [{ b: 'Population Density Mapping' }, ' for demographic and planning insights'],
          [{ b: 'Land Cover Analysis' }, ' to understand land usage patterns'],
          [{ b: 'Flight Flow Mapping' }, ' for visualizing air traffic movement and regional connectivity'],
        ],
      },
      { type: 'para', runs: ['These research efforts help build a strong foundation for integrating geographic, environmental, and infrastructure data into telecom and other data-driven applications.'] },
      {
        type: 'gallery',
        items: [
          { image: 'gis-elevation', alt: 'Elevation mapping' },
          { image: 'gis-rainfall', alt: 'Rainfall data analysis' },
          { image: 'gis-soil-pakistan', alt: 'Soil mapping of Pakistan' },
          { image: 'gis-temperature', alt: 'Temperature data visualization' },
          { image: 'gis-uae-administration', alt: 'UAE administrative boundaries' },
          { image: 'gis-uae-industrial-transport', alt: 'UAE industrial areas and transportation' },
          { image: 'gis-uae-population', alt: 'UAE population density' },
          { image: 'gis-world-flow-map', alt: 'World flight-flow map' },
          { image: 'gis-islamabad', alt: 'Islamabad land cover' },
          { image: 'gis-dubai-rainfall', alt: 'Dubai rainfall' },
          { image: 'gis-dubai-land', alt: 'Dubai land cover' },
          { image: 'gis-uae-temperature', alt: 'UAE temperature' },
          { image: 'gis-iran-geology', alt: 'Geology of Iran' },
          {
            image: 'gis-pakistan-rivers-map',
            alt: 'Pakistan rivers interactive map',
            href: 'https://xflowresearch.com/pakistan-rivers',
            caption: 'View interactive map',
          },
          {
            image: 'gis-pakistan-universities-map',
            alt: 'Pakistan universities interactive map',
            href: 'https://xflowresearch.com/pakistan-universities',
            caption: 'View interactive map',
          },
        ],
      },
      {
        type: 'embed',
        title: 'Interactive Maps',
        frames: [
          {
            label: 'LST UTF VI in UAE',
            src: 'https://ee-shak5121472.projects.earthengine.app/view/lstutfvi-in-uae',
            title: 'Land Surface Temperature & UTFVI in UAE',
          },
          {
            label: 'Annual Temperature',
            src: 'https://ee-shak5121472.projects.earthengine.app/view/annual-temperature',
            title: 'Annual Temperature',
          },
        ],
      },
    ],
  },
  'gis-in-telecommunication': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech is also conducting research and development in Geographic Information Systems (GIS) for telecom use cases. Our work focuses on using location-based data to improve network visibility, analysis, and operational decision-making.'] },
      { type: 'heading', text: 'Proofs of Concept (PoCs)' },
      { type: 'para', runs: ['As part of our R&D efforts, we have developed several proof-of-concept solutions with synthetic data, including:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          [{ b: 'Mapping of 4G and 5G Cell IDs' }, ' — Visualization and mapping of 4G and 5G cell identifiers across a region to support network planning and analysis.'],
          [{ b: 'Real-Time Call Load per Cell ID' }, ' — Monitoring and visualization of real-time call load distribution across different cell IDs within a region.'],
          [{ b: 'Connected UE / Device Information' }, ' — Mapping of connected user equipment (UEs) and devices associated with specific cell IDs to provide visibility into network usage patterns.'],
        ],
      },
      {
        type: 'gallery',
        items: [
          { image: 'gis-telco-cell-ids', alt: '4G/5G cell IDs and call load' },
          { image: 'gis-telco-uae-sectors', alt: 'UAE network sectors' },
        ],
      },
    ],
  },
  'monitoring-solutions': {
    blocks: [
      { type: 'para', runs: ['At xFlow Tech, we design and implement monitoring solutions tailored to your infrastructure: whether it’s network, hardware, or applications.'] },
      { type: 'para', runs: ['Our services are focused on the tools including:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Prometheus for time-series metrics'],
          ['Grafana for visual dashboards'],
          ['ELK for log analysis'],
          ['Zabbix for overall system monitoring.'],
        ],
      },
      { type: 'para', runs: ['Our team ensures that alerts are properly set up and routed to the right channels, such as email, Slack, or other systems, so issues are caught and addressed quickly.'] },
    ],
  },
  'nfv': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech Inc. offers specialized services in Network Function Virtualization (NFV). Our focus in NFV is on Research and development related to NFVI, VNF, and MANO. We provide industry leading technology development that will enable you to quickly demonstrate, develop and market your ideas.'] },
      { type: 'para', runs: ['We also offer our services to extend your existing projects/products in the revolutionary NFV domain. We bring agility to product development lifecycle by developing automation tools to quickly demonstrate and market your products in NFV domain.'] },
      { type: 'para', runs: ['We are actively involved in Research and Development in NFV and have successfully completed PoC projects with industry leaders in NFV.'] },
      { type: 'heading', text: 'vBRAS' },
      { type: 'para', runs: ['Virtual B-RAS is intended to be a product for ISP. It authenticates, authorizes and routes subscriber data traffic. VBRAS also provides policy enforcement features.'] },
      { type: 'heading', text: 'VNF' },
      { type: 'para', runs: ['We provide industry-standard deployment, integration, testing and benchmarking of a wide variety of VNFs.'] },
      { type: 'heading', text: 'NFVI' },
      { type: 'para', runs: ['Our services include designing and development of Compute, Control, Network and Storage blend that can build an efficient scalable NFV solution.'] },
      { type: 'heading', text: 'MANO' },
      { type: 'para', runs: ['xFlow Tech provides state-of-the-art development, integration and testing services in Management and Network Orchestration.'] },
    ],
  },
  'open-source-contributions-and-development': {
    blocks: [
      { type: 'para', runs: ['We are members of the ', { b: 'CAMARA open-source project under the Linux Foundation' }, ' and contribute to its ongoing development and evolution.'] },
      { type: 'heading', text: 'CAMARA DeviceAuthenticity API' },
      { type: 'para', runs: ['xFlow Tech has successfully introduced the ', { b: 'Device Authenticity API' }, ' within the CAMARA project. We serve as the', { b: ' owner of this API repository' }, ' and actively contribute to its maintenance and future enhancements.'] },
      { type: 'para', runs: ['As part of this role, xFlow Tech:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Coordinates technical discussions and meetings related to this sandboxed API'],
          ['Ensures alignment across proposals from participating organizations'],
          ['Works closely with stakeholders to maintain consistency with CAMARA standards'],
        ],
      },
      { type: 'para', runs: ['Initial interested parties for the DeviceAuthenticity API include ', { b: 'MTN Chenosis' }, ' and the ', { b: 'GSMA Device Check service' }, '.'] },
      { type: 'heading', text: 'CAMARA API Dashboard' },
      { type: 'para', runs: ['We have developed a ', { b: 'CAMARA API Dashboard' }, ', a web-based management and monitoring interface for testing ', { b: '5G Network APIs' }, ' that follow the CAMARA standard.'] },
      { type: 'para', runs: ['The dashboard is built using ', { b: 'Next.js and TypeScript' }, ' and provides a unified platform for interacting with APIs such as:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Quality on Demand (QoD)'],
          ['Device Location'],
          ['Traffic Influence'],
        ],
      },
      { type: 'para', runs: ['The current implementation integrates with EUROCOM’s 5G CoreSim (Core Simulation) environment. Support for additional 5G core platforms, including Free5GC, Open5GS, and OpenAirInterface (OAI), is planned for future releases.'] },
      { type: 'heading', text: 'Architecture and Capabilities' },
      { type: 'para', runs: ['The dashboard connects to 5G core environments through the ', { b: 'TF-SDK (Transformation Function) middleware layer' }, ', enabling:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Real-time monitoring'],
          ['Service discovery'],
          ['Interactive visualizations, including location maps and network flow diagrams'],
        ],
      },
      { type: 'heading', text: 'Ongoing Enhancements' },
      { type: 'para', runs: ['We are continuously improving the platform, with current work focused on:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Authentication and access control'],
          ['WebSocket-based real-time updates'],
          ['Additional 5G core adapters'],
          ['Improved API documentation'],
          ['Component guides and deployment instructions'],
        ],
      },
      { type: 'para', runs: [{ b: 'xFlow Tech' }, ' actively contributes to the ', { b: 'Community SONiC' }, ' project by developing new features, fixing bugs, and improving the performance and stability of existing components. Our work focuses on practical enhancements that align with real operational requirements.'] },
      { type: 'heading', text: 'Contribution Highlights' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Active contributor to Community SONiC across multiple releases'],
          ['Served as reviewers for two features in the 2023-11 feature release — one from Microsoft (MSFT), one from NVIDIA'],
          ['Contributed multiple pull requests (PRs) across different SONiC containers'],
          ['Assisted the SONiC community in building custom SONiC images from scratch'],
          ['Participated in SONiC Hackathon 2022 and SONiC Hackathon 2023'],
          ['Regular participant in SONiC community weekly review meetings'],
          ['Member of the Linux Foundation'],
        ],
      },
      { type: 'heading', text: 'Community Contribution Services' },
      { type: 'para', runs: ['In addition to our direct contributions, we support customers who request community contributions on their behalf. We provide services that include:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Feature development aligned with community standards'],
          ['Bug fixes and upstream submissions'],
          ['Code reviews and release alignment'],
          ['Coordination with the SONiC community to ensure smooth acceptance and integration'],
        ],
      },
      { type: 'para', runs: ['This approach helps customers contribute effectively to the SONiC ecosystem while maintaining alignment with upstream development practices.'] },
    ],
  },
  'professional-services': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech offers a range of IT services to meet the unique needs of our clients. Our expertise includes the deployment of IT infrastructure, managed services, on-premises support, monitoring and remote technical assistance. Our primary focus is to provide exceptional service and ensure customer satisfaction.'] },
      { type: 'para', runs: ['Our services include:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Managing projects from start to finish, including planning, execution, and monitoring'],
          ['Developing custom software applications to meet clients’ specific business needs'],
          ['Solution Architecture'],
          ['Technology/Vendor Assessment'],
          ['Designing and setting up IT infrastructure, including network design, server deployment, and storage solutions'],
          ['Protecting clients’ networks and systems from cyber threats, including threat assessments, security audits, and incident response'],
          ['Automation'],
          ['Managed Services'],
          ['Network Planning and Monitoring'],
          ['Remote services'],
        ],
      },
      { type: 'para', runs: ['We serve markets globally.'] },
    ],
  },
  'project-management': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech specializes in providing end-to-end ', { b: 'Project Management Services' }, ' designed to ensure successful delivery, transparency, and alignment with business goals. Our approach is structured, detail-oriented, and flexible to support a wide range of industries and project types.'] },
      { type: 'para', runs: ['Our project management services include:'] },
      { type: 'heading', text: 'Project Initiation & Planning' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Defining scope, objectives, and deliverables'],
          ['Resource planning and stakeholder alignment'],
          ['Budget estimation and timeline development'],
        ],
      },
      { type: 'heading', text: 'Execution & Delivery' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Coordinating tasks and team members'],
          ['Tracking progress and ensuring milestones are met'],
          ['Managing communications and documentation'],
        ],
      },
      { type: 'heading', text: 'Project Control & Monitoring' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Risk management and issue resolution'],
          ['Budget tracking, PO (Purchase Order) management, and quotation handling'],
          ['Quality assurance and scope control'],
        ],
      },
      { type: 'heading', text: 'Project Closure' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Final deliverables review and approval'],
          ['Post-implementation evaluation and reporting'],
          ['Documentation handover and client feedback'],
        ],
      },
      { type: 'heading', text: 'Additional Services Supporting Project Success' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Technology and vendor assessments'],
          ['Solution architecture design'],
          ['Infrastructure design and deployment (as needed for technical projects)'],
          ['Process automation and reporting support'],
          ['Remote and on-site coordination as required'],
        ],
      },
      { type: 'para', runs: ['We serve clients across the globe, bringing structured project management methodologies, experienced teams, and a results-driven mindset to every project we manage.'] },
    ],
  },
  'quantum-research': {
    blocks: [
      { type: 'heading', text: 'Driving Innovation: Our Quantum Journey' },
      { type: 'para', runs: ['At xFlow Tech, we believe quantum technology will reshape the future of computing and security. As computers become more powerful, the way we protect data must evolve too. That is why we are building a team of researchers and engineers dedicated to exploring these new technologies. Our work combines deep study, hands-on testing, and strong partnerships to stay ahead of the curve. Together, we are turning complex quantum science into practical tools that help keep the digital world secure.'] },
      { type: 'heading', text: 'Our Role in Addressing the Quantum Threat' },
      { type: 'para', runs: ['Quantum computers will soon break today’s security locks. We are working to stay ahead of this challenge. Our team specializes in two approaches: Quantum Key Distribution (QKD), which uses the laws of physics to share secure keys, and Quantum-Safe Cryptography (QSC), which uses new mathematical locks that quantum computers cannot crack. We are actively helping to shape global security standards and have already deployed ML-KEM, the new NIST-approved quantum-safe algorithm, into our own systems. We are also building a Quantum-Safe VPN that uses this technology to create a secure tunnel, protecting data from the “harvest now, decrypt later” threat.'] },
      { type: 'heading', text: 'Protection against Quantum Computers' },
      { type: 'para', runs: ['At xFlow Tech, we are working on new ways to protect data against this future threat. Our approach combines two strategies: Quantum Key Distribution (QKD), which uses the laws of physics to share secure keys, and Post-Quantum Cryptography (PQC), which uses advanced mathematics to create locks that quantum computers cannot crack. We are also helping to shape global security standards to ensure these new protections are adopted worldwide.'] },
      { type: 'heading', text: 'PQC' },
      { type: 'para', runs: ['Post-Quantum Cryptography, or PQC, refers to new cryptographic algorithms designed to be secure against both classical and quantum computers. Think of it as upgrading your locks to ones that even the most powerful future tools cannot pick. Unlike QKD, which requires specialized hardware, PQC works entirely through software and can be deployed on existing systems. This makes it a practical and scalable solution for protecting data today and in the future. We are actively studying and implementing these new algorithms, contributing to global standardization efforts, and helping organizations transition to quantum-safe security.'] },
      { type: 'heading', text: 'ML-KEM' },
      { type: 'para', runs: ['ML-KEM (Module-Lattice-Based Key-Encapsulation Mechanism) is one of the first NIST-approved post-quantum cryptographic standards. In simple terms, it is a new way to securely exchange encryption keys between two parties even if a quantum computer is trying to intercept them. We have already deployed ML-KEM within our own infrastructure and are building practical applications around it. To help others understand this technology, we have created an Interactive ML-KEM Visualizer, a free educational web app that breaks the complex math into simple, step-by-step animations. Users can watch how keys are generated and exchanged in real-time, making this cutting-edge technology accessible to everyone.'] },
      { type: 'heading', text: 'McEliece' },
      { type: 'para', runs: ['The McEliece cryptosystem is one of the oldest and most well-studied post-quantum encryption schemes. It is based on the hardness of decoding random linear codes, a problem believed to be resistant to both classical and quantum attacks. Unlike lattice-based schemes, McEliece offers fast encryption and decryption, making it attractive for certain use cases. Its main trade-off is “larger key sizes”, but ongoing research is addressing these challenges. We are investigating McEliece as a potential alternative or complement to other PQC algorithms in our security architecture.'] },
      { type: 'heading', text: 'Digital Signatures, From Classical to Quantum' },
      { type: 'para', runs: ['Digital signatures are the backbone of trust in the digital world. They ensure that a message, document, or piece of software truly comes from who it claims to come from and hasn’t been altered along the way. Whether you are signing an email, verifying a software update, or authenticating a financial transaction, digital signatures make it all possible.'] },
      { type: 'para', runs: ['To help demystify this critical technology, we have built an interactive web app that walks you through the entire journey of signatures. Starting with the basic concept of what a signature is, moving through classical cryptographic signatures (like RSA and ECDSA), and finally exploring how quantum-safe signatures work to protect against future quantum threats.'] },
      { type: 'para', runs: ['Our app is designed for everyone, whether you are a student, developer, or a security professional. You don’t need a background in cryptography to get started. Through simple animations and step-by-step explanations, you will learn:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['What makes a signature secure'],
          ['How classical signatures work under the hood'],
          ['Why quantum computers break them'],
          ['What are post-quantum signature schemes offering a solution'],
        ],
      },
      { type: 'para', runs: ['No matter your level of expertise, this tool will give you a clear, intuitive understanding of how signatures protect your digital life both today and in the quantum future.'] },
      { type: 'heading', text: 'Interactive Quantum Visualizations' },
      { type: 'para', runs: ['To complement our theoretical research and experimental implementations, xFlow Tech has developed a set of interactive HTML-based visualizations that intuitively demonstrate key quantum and photonic concepts. These visual tools are designed to bridge the gap between abstract quantum theory and physical intuition, making complex ideas easier to explore and understand.'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['BB84 Quantum Key Distribution Protocol'],
          ['Optical Phenomena Dashboard'],
          ['Time-Bin Coding Quantum Communication'],
          ['Quantum Orbitals showing Quantum Numbers'],
        ],
      },
      { type: 'heading', text: 'Strategic Research, Evaluation, and Collaboration' },
      { type: 'para', runs: ['Beyond training, we have moved into active research and evaluation of quantum resources, coupled with strategic outreach to academic experts.'] },
      {
        type: 'list',
        ordered: false,
        items: [
          [{ b: 'Quantum Algorithms and Use-Cases:' }, ' We have initiated the study of core Quantum Algorithms to understand their potential applications across our business domains.'],
          [{ b: 'Hardware Evaluation: ' }, 'We are conducting a thorough evaluation of different mini quantum computers to inform future internal Proof-of-Concepts (PoCs).'],
          [{ b: 'Hands-on Quantum Development:' }, ' Beyond theoretical evaluation, our team engages in practical experimentation and development using Qiskit and the IBM Quantum Runtime. This hands-on approach allows us to validate quantum concepts through real quantum hardware and simulations, directly informing our internal PoCs and deepening our understanding of the practical constraints and capabilities of today’s quantum processors.'],
        ],
      },
      { type: 'heading', text: 'Future Roadmap' },
      { type: 'para', runs: ['Our commitment to quantum technology is a long-term strategy. Building on our strong foundation, our immediate and near-term plans are focused on concrete development, expansion of partnerships, and the execution of high-impact PoCs.'] },
      {
        type: 'list',
        ordered: false,
        items: [
          [{ b: 'Qiskit Advocate:' }, ' We will demonstrate a higher level of proficiency and contribution to the quantum open-source community, achieving higher levels of expertise.'],
          [{ b: 'Establishing Strategic Alliances:' }, ' We plan to explore and prepare with different companies. This initiative is aimed at combining our internal expertise with external market leaders to accelerate our development.'],
          [{ b: 'Executing Internal PoCs:' }, ' We will leverage the results of our hardware evaluation to launch many internal Proof-of-Concepts. These PoCs will focus on validating quantum advantages in specific areas relevant to xFlow Tech. Our QVPN project already serves as a prime example of this approach, validating quantum-safe networking protocols in a live operational environment while ensuring strict alignment with the emerging ETSI QKD and QSC specifications we actively contribute to'],
          [{ b: 'Advanced Research & Standardization:' }, ' We will move to applied research, focusing on advanced quantum protocols and algorithms to further strengthen our internal capabilities and intellectual property. This work will also feed directly into our contributions to the ETSI ISG QKD and ETSI CYBER_QSC specifications, including Application Interfaces (API) and Protection Profiles.'],
        ],
      },
      { type: 'para', runs: ['By investing heavily in our team’s knowledge, strategic partnerships, and hands-on hardware evaluation, xFlow Tech is actively shaping a future where we utilize quantum technology to deliver unprecedented value and innovation.'] },
      { type: 'heading', text: 'Quantum Experiments' },
      { type: 'para', runs: ['Our commitment to transparent and collaborative research is demonstrated through our public code contributions. Our team maintains strong alignment with the global open-source quantum ecosystem, ensuring that our research output reflects current best practices and actively contributes to the broader quantum community. Through continuous learning, experimentation, and standards-driven research, xFlow Tech collectively advances the development of robust, quantum-safe architectures. You can explore the technical depth of our work, including various Qiskit algorithm implementations and quantum simulations, on GitHub:'] },
    ],
  },
  'research-and-standardization': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech is a full-time member of European Telecommunication Standards Institute (ETSI) which sets standards for cutting technologies like NFV, MEC, IoT, Smart Cities, Augmented Reality. Engineers from xFlow Tech work closely with ETSI in different domains like Conformance and Interoperability testing, Development of Simulation and other Educational Tools based on the ETSI specifications, Export Support in Plugtests, and many more.'] },
      { type: 'para', runs: ['Following are the competencies and related work described in terms of our ETSI engagement and participation in Specialist Task Forces (STFs) and Testing Task Forces (TTFs):'] },
      { type: 'para', runs: ['xFlow Tech also participates in different activities conducted by ETSI:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Part of the Plugtests Team in “Expert” capacity for organizing and supporting the ', { b: 'NFV&MEC IOP Plugtests 2021' }, ' event'],
          ['Participated as an NFVI provider in the ETSI ', { b: 'NFV&MEC API Plugtests 2021' }, ' event'],
          ['Participated as a “Technical Expert” in organizing the ', { b: '4th NFV Plugtests' }, ' event'],
          ['Founding member of ', { b: 'OSM community' }],
          ['Contributed to ', { b: '6th OSM Hackfest' }],
          ['Provided expert support in the ', { b: 'OSM-MR13 Hackfest 2022' }, ' by setting up VMs for the participants, wrote a Blog Post, and edited Hackfest videos'],
          ['Presenting our experiences of using different automated testing techniques at the ', { b: '8th User Conference on Advanced Automated Testing (UCAAT)' }],
        ],
      },
    ],
  },
  'software-development': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech provides software development services focused on building reliable, efficient, and maintainable systems. We follow established software development standards and a structured ', { b: 'Software Development Life Cycle (SDLC)' }, ' to ensure quality, consistency, and predictable outcomes. We work closely with our clients to understand their requirements and deliver solutions that meet both technical and business needs.'] },
      { type: 'heading', text: 'Our Services' },
      { type: 'heading', text: 'Software Development' },
      { type: 'para', runs: ['We design and develop high-performance software using C, C++, Golang, and Python, following industry-accepted coding standards, secure development practices, and structured development workflows.'] },
      { type: 'heading', text: 'Customized Software Solutions' },
      { type: 'para', runs: ['We build tailored software solutions based on specific business and technical requirements, developed and validated through a defined SDLC process.'] },
      { type: 'heading', text: 'API Development' },
      { type: 'para', runs: ['We develop secure, well-documented APIs designed for integration, scalability, and long-term maintainability.'] },
      { type: 'heading', text: 'Web and App Development' },
      { type: 'para', runs: ['We deliver web and application solutions with a focus on usability, performance, and reliability.'] },
      { type: 'heading', text: 'Quality and Engineering Practices' },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Structured SDLC covering requirements, design, implementation, testing, and deployment'],
          ['Unit testing as part of development to ensure correctness and reduce regressions'],
          ['Code reviews and version control to maintain consistency and quality'],
          ['Emphasis on maintainable, well-documented code'],
        ],
      },
    ],
  },
  'sonic': {
    blocks: [
      { type: 'para', runs: ['xFlow Tech Inc. is an active member of Community SONiC and has contributed in many ways to Community SONiC.'] },
      { type: 'para', runs: ['Our team of experts deeply understands SONiC and its capabilities, and we are here to help you get the most out of this cutting-edge technology.'] },
      { type: 'para', runs: ['Why is SONiC essential for data centers?'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['SONiC promotes vendor neutrality and open ecosystems, allowing users to select and customize hardware without lock-in.'],
          ['Its modular architecture and community support drive innovation, scalability, and reduced total cost of ownership.'],
          ['The unified interface simplifies management, while interoperability testing ensures compatibility and future-proofing.'],
          ['SONiC’s open-source nature fosters agility, enabling quick adaptation to industry trends and continuous improvements.'],
        ],
      },
      { type: 'para', runs: ['Our team can help you make your network reliable, secure, robust, and agile through network programmability and automation technologies.'] },
      { type: 'para', runs: ['What do we offer in the realm of SONiC?'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Architecture and Design'],
          ['Support Services'],
          ['Product Enhancements'],
          ['Product Development'],
          ['Deployments'],
          ['Configuration Services'],
          ['Migration Services'],
          ['Test Plans & Testing'],
        ],
      },
      { type: 'para', runs: ['Our contributions to SONiC include the following features:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['Switch Port Modes and VLAN CLI Enhancement'],
          ['Multiple Spanning Tree (MST)'],
          ['DHCP DOS Mitigation Support'],
          ['Test Plan HLD for OSPF'],
          ['Test Plan HLD for BFD Echomode'],
          ['Test Plan HLD for BFD with OSPF'],
          ['Switch Port Mode Hybrid'],
          ['MAC based VLAN Assignment'],
        ],
      },
    ],
  },
  'testing-and-validation': {
    blocks: [
      { type: 'para', runs: ['We help you deliver reliable and bug-free software by offering ', { b: 'quality assurance (QA)' }, ' ', { b: 'services' }, ' for mobile apps, web apps, and software products. Our testing approach follows global standards and is based on ', { b: 'ISTQB foundational knowledge.' }, ' We cover every phase of the ', { b: 'Software Testing Life Cycle (STLC)' }, ' with a focus on practical, real-world application.'] },
      { type: 'para', runs: ['Our QA services include:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          [{ b: 'Functional Testing:' }, ' Verify that all features work as expected according to requirements'],
          [{ b: 'Integration Testing:' }, ' Ensure different components and systems work well together'],
          [{ b: 'Performance Testing:' }, ' Check how your application performs under load or stress'],
          [{ b: 'Manual Testing:' }, ' In-depth, hands-on testing for user experience'],
          [{ b: 'Automated Testing:' }, ' Automation of repetitive test cases using tools like Selenium & Cypress and frameworks including Pytest & Robot'],
          [{ b: 'Bug Reporting & Validation:' }, ' Clear issue tracking, reporting, and regression testing to confirm fixes'],
        ],
      },
      { type: 'para', runs: ['We work side-by-side with your development team to improve product quality, speed up release cycles, and ensure the software meets the requirements and is bug free.'] },
    ],
  },
  'training-services': {
    blocks: [
      { type: 'heading', text: 'Training' },
      { type: 'para', runs: ['We provide training services and certifications to companies, educational institutions. The training can be a 1 day seminar covering basics on OpenStack and architecture, or a 3 day workshop including OpenStack deployments, debugging and development categorized under different learning modules. The training duration can also vary based on customized learning requirements.'] },
      { type: 'heading', text: 'OpenStack Introductory Seminar' },
      { type: 'para', runs: ['This purpose of this one day seminar is to introduce OpenStack to the audience. It includes introduction to clouds, cloud deployment, role of OpenStack, reasons to use OpenStack in your setup and features of OpenStack.'] },
      { type: 'heading', text: 'OpenStack Associate Training & Certification' },
      { type: 'para', runs: ['This three day training is designed for IT professionals who are looking to gain basic knowledge on OpenStack. This training offers basic understanding of all the OpenStack modules. It covers brief history on OpenStack, motivations for worldwide adoption and support, introduction to OpenStack and its modules along with their functionality, working and interconnection details. In the hands on section, this training will enable the participants to install OpenStack and its modules, configure them and for use OpenStack services via the client tools and the dashboard. This training is the best preparation for new users trying to learn OpenStack from scratch and want to have a running OpenStack deployment.'] },
      { type: 'heading', text: 'OpenStack Administrator Training & Certification' },
      { type: 'para', runs: ['This three day will cover some advanced topics in OpenStack. This training is ideal for individuals who know the basics of OpenStack and want to get a deeper insight into the working on OpenStack and its modules. This will enable participants to configure OpenStack deployment in a wide variety of ways and to test various settings and configurations. This will include explanation of the configuration files, how to interpret logs, correct errors, description of command workflows and some deployment scenarios. The hands-on demonstration for this training will include testing of custom configurations, exploring log files and their explanation and correction of errors by looking at log files.'] },
      { type: 'heading', text: 'OpenStack Developer Training & Certification' },
      { type: 'para', runs: ['This three day training is best suited for OpenStack administrators who want to start developing OpenStack and contributing to the OpenStack community. This training will cover development, debugging OpenStack code base, explanation of OpenStack APIs/REST calls, writing a sample OpenStack extension and grass-root level details on OpenStack. Participants will also learn coding practices and methods of contributing in the OpenStack community.'] },
      { type: 'heading', text: 'OpenStack Customized Training & Certification' },
      { type: 'para', runs: ['To maximize flexibility, we also offer private OpenStack trainings, which are tailored to suit your needs. This training is specially designed for customers with specific requirements. We let the customer decide on what they want to learn and what type of training they require. Based on the requirements we design a training outline and content as well. The duration for such an activity depends on the customer requirements.'] },
      { type: 'para', runs: ['We have provided OpenStack training, workshops & certificates at the following institutions:'] },
      {
        type: 'list',
        ordered: false,
        items: [
          ['National University of Science and Technology (NUST)'],
          ['National University of Computer & Emerging Sciences (FAST-NUCES)'],
          ['Mehran University of Engineering & Technology, Jamshoro'],
          ['Namal College, Mianwali'],
        ],
      },
    ],
  },
  'vulnerability-assessment-services': {
    blocks: [
      { type: 'para', runs: ['The purpose of Vulnerability and Scan Services is to identify potential security threats and vulnerabilities in a company’s online systems and to provide the necessary tools and resources to remediate them. The goal is to prevent cyber-attacks, protect sensitive data, and maintain compliance with industry standards.'] },
      { type: 'para', runs: ['Vulnerability and Scan Services are a comprehensive suite of tools and services that are designed to help companies identify, assess, and mitigate security threats. These services utilize state-of-the-art technology and industry-leading best practices to provide a comprehensive security solution.'] },
      { type: 'para', runs: [{ b: 'Vulnerability Scanning:' }, ' Perform a thorough scan of your network to identify any potential vulnerabilities that could be exploited by cybercriminals. Provide a detailed report of our findings, along with recommendations for remediation and ways to improve your overall security posture.'] },
      { type: 'para', runs: [{ b: 'Penetration Testing:' }, ' Offer simulated attacks to test the strength of your defenses and identify any weaknesses that need to be addressed. Our goal is to help proactively detect and mitigate potential threats before they cause harm.'] },
      { type: 'para', runs: [{ b: 'Compliance Scanning:' }, ' It is designed to help meet regulatory requirements and ensure systems are in compliance with industry standards. Providing customized solutions to help you maintain compliance and protect sensitive data.'] },
      { type: 'para', runs: [{ b: 'Continuous Monitoring:' }, ' It includes ongoing monitoring to ensure systems remain secure and to promptly detect any new vulnerabilities that may arise. It is to be believed that a proactive and informed approach to security is key to reducing risk and mitigating potential threats.'] },
    ],
  },
  'web-application': {
    blocks: [
      { type: 'para', runs: [{ b: 'xFlow Tech' }, ' provides end-to-end web application development services, covering design, development, deployment, and ongoing support. Our approach focuses on building reliable, scalable, and maintainable web applications that meet functional and performance requirements.'] },
      { type: 'heading', text: 'Our Web Application Services Include' },
      { type: 'heading', text: 'Custom Web Application Development' },
      { type: 'para', runs: ['Design and development of web applications tailored to specific business and technical needs.'] },
      { type: 'heading', text: 'Frontend Development' },
      { type: 'para', runs: ['Development of user interfaces with a focus on usability, accessibility, and consistency across devices and browsers.'] },
      { type: 'heading', text: 'Backend Development' },
      { type: 'para', runs: ['Implementation of secure and scalable backend services, business logic, and data handling.'] },
      { type: 'heading', text: 'Responsive UI/UX Design' },
      { type: 'para', runs: ['Design of responsive user interfaces that adapt across desktop, tablet, and mobile platforms.'] },
      { type: 'heading', text: 'API Development and Integration' },
      { type: 'para', runs: ['Development and integration of APIs for internal services and third-party systems.'] },
      { type: 'heading', text: 'Database Design and Management' },
      { type: 'para', runs: ['Database schema design, optimization, and management to support application reliability and performance.'] },
      { type: 'heading', text: 'Web Application Performance Optimization' },
      { type: 'para', runs: ['Performance tuning to improve response times, scalability, and resource efficiency.'] },
      { type: 'heading', text: 'Deployment and Maintenance Support' },
      { type: 'para', runs: ['Support for application deployment, upgrades, monitoring, and ongoing maintenance.'] },
    ],
  },
};
